language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

os:
    - linux


python:

    - 2.7
    - 3.4
    - 3.5

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - SETUPTOOLS_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install -c astropy-ci-extras --yes'
        - PIP_INSTALL='pip install'
        - INSTALL_OPTIONAL=true
        - SETUP_CMD='test'
        - NUMPY_VERSION=1.10

before_install:

    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST
    # FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8

    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    #CHECK INTERACTIVE MATPLOTLIB BACKENDS
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start



install:
    - conda create -c astropy-ci-extras --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # ADD STSCI ASTROCONDA CHANNEL
    - conda config --add channels http://ssb.stsci.edu/astroconda

    # CORE DEPENDENCIES
    - $CONDA_INSTALL -n test  numpy=$NUMPY_VERSION calcos crds=6.0

    # ASTROPY
    - $PIP_INSTALL git+http://github.com/astropy/astropy.git#egg=astropy
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION astropy


    # OPTIONAL DEPENDENCIES
    # Here you can add any dependencies your package may have. You can use
    # conda for packages available through conda, or pip for any other
    # packages. You should leave the `numpy=$NUMPY_VERSION` in the `conda`
    # install since this ensures Numpy does not get automatically upgraded.
    - $CONDA_INSTALL -n test numpy=$NUMPY_VERSION scipy matplotlib pyyaml sqlalchemy numpydoc beautifulsoup4 psutil

    # DOCUMENTATION DEPENDENCIES
    # build_sphinx needs sphinx and matplotlib (for plot_directive).
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL -n test numpy=$NUMPY_VERSION Sphinx matplotlib; fi


script:
   - python setup.py install
   - nosetests
